Tp5/Tp5/Tp5/Areas/Admin/ViewModels/SiteMessageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Tp5.Areas.Admin.ViewModels
{
    public class SiteMessageViewModel
    {
        public string Message { get; set; }
    }
}

Tp5/Tp5/Tp5/Areas/Admin/Controllers/MenuController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tp5.Areas.Admin.ViewModels;
using Tp5.DataAccessLayer;
using Tp5.Models;

namespace Tp5.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class MenuController : Controller
    {
        public IActionResult List()
        {
            DAL dal = new DAL();
            ListMenuViewModel viewModel = new ListMenuViewModel
            {
                Menus = dal.MenuFactory.GetAll()
            };

            return View(viewModel);

        }

        public IActionResult Create()
        {
            DAL dal = new DAL();

            CreateEditMenuViewModel viewModel = new CreateEditMenuViewModel
            {
                Menu = dal.MenuFactory.CreateEmpty(),
            };

            return View("CreateEdit", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CreateEditMenuViewModel viewModel)
        {
            if (viewModel != null && viewModel.Menu != null)
            {
                DAL dal = new DAL();

                Menu existingMenu = dal.MenuFactory.Get(viewModel.Menu.id);
                if (existingMenu != null)
                {
                    // Il est possible d'ajouter une erreur personnalisée.
                    // Le premier paramètre est la propriété touchée (à partir du viewModel ici)
                    ModelState.AddModelError("Menu.Id", "Le id de menu existe déjà.");
                    viewModel.Menus = dal.MenuFactory.GetAll();
                    return View("CreateEdit", viewModel);
                }

                // Si le modèle n'est pas valide, on retourne à la vue CreateEdit où les messages seront affichés.
                // Le ViewModèle reçu en POST n'est pas complet (seulement les info dans le <form> sont conservées),
                // il faut donc réaffecter les Catégories.
                if (!ModelState.IsValid)
                {
                    viewModel.Menus = dal.MenuFactory.GetAll();
                    return View("CreateEdit", viewModel);
                }

                dal.MenuFactory.Save(viewModel.Menu);
            }

            return RedirectToAction("List");
        }

        public IActionResult Edit(int id)
        {
            if(id > 0)
            {
                DAL dal = new DAL();
                Menu menu = dal.MenuFactory.Get(id);

                if(menu != null)
                {
                    CreateEditMenuViewModel viewModel = new CreateEditMenuViewModel
                    {
                        Menu = menu,
                    };
                    return View("CreateEdit",viewModel);
                }                       
            }
            return View("SiteMessage", new SiteMessageViewModel
            {
                Message = "L'identifiant du menu est introuvable (Admin/Menu/" + id + ")."
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, CreateEditMenuViewModel viewModel)
        {
            if (viewModel != null && viewModel.Menu != null)
            {
                DAL dal = new DAL();

                Menu existingmenu = dal.MenuFactory.Get(viewModel.Menu.id);
                if (existingmenu != null && existingmenu.id != viewModel.Menu.id)
                {
                    // Il est possible d'ajouter une erreur personnalisée.
                    // Le premier paramètre est la propriété touchée (à partir du viewModel ici)
                    ModelState.AddModelError("menu.Id", "Le id de menu existe déjà.");
                    viewModel.Menus = dal.MenuFactory.GetAll();
                    return View("CreateEdit", viewModel);
                }

                // Si le modèle n'est pas valide, on retourne à la vue CreateEdit où les messages seront affichés.
                // Le ViewModèle reçu en POST n'est pas complet (seulement les info dans le <form> sont conservées),
                // il faut donc réaffecter les Catégories.
                if (!ModelState.IsValid)
                {
                    viewModel.Menus = dal.MenuFactory.GetAll();
                    return View("CreateEdit", viewModel);
                }

                dal.MenuFactory.Save(viewModel.Menu);
            }

            return RedirectToAction("List");
        }

        public IActionResult Delete(int id)
        {
            if(id > 0)
            {
                DAL dal = new DAL();
                Menu menu = dal.MenuFactory.Get(id);

                if(menu != null)
                {
                    ListMenuViewModel viewModel = new ListMenuViewModel
                    {
                        Menu = menu,
                        Menus = dal.MenuFactory.GetAll(),
                    };
                    return View(viewModel);
                }
                               
            }

            return View("SiteMessage", new SiteMessageViewModel
            {
                Message = "L'identifiant du menu est introuvable (Admin/Menu/" + id + ")."
            });
        }

        // POST: Admin/Product/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id, IFormCollection collection)
        {
            if (id > 0)
            {
                new DAL().MenuFactory.Delete(id);
            }

            return RedirectToAction("List");
        }
    }
}

Tp5/Tp5/Tp5/Controllers/ReservationController.cs
using Microsoft.AspNetCore.Mvc;
using Tp5.ViewModel;
using Tp5.DataAccessLayer;
using Tp5.Models;

namespace Tp5.Controllers
{
    public class ReservationController : Controller
    {
        public IActionResult Details(int id)
        {
            DAL dal = new DAL();
            Reservation reservation = dal.reservationFactory.Get(id);

            if(reservation != null)
            {
                DetailsViewModel viewModel = new DetailsViewModel
                {
                    Reservation = reservation,
                };

                return View(viewModel);
            }
            return View("SiteMessage", new SiteMessagesViewModel
            {
                Message = "L'identifiant de la reservation est introuvable."
            });
        }
    }
}

Tp5/Tp5/Tp5/Areas/Admin/Views/Shared/SiteMessage.cshtml
@model SiteMessageViewModel
@{
    ViewData["Title"] = "Message";
}

<div id="message-page">
    <div class="page-title">
        <h2>Message</h2>
    </div>

    <p>@Model.Message</p>
</div>

Tp5/Tp5/Tp5/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>@ViewData["Title"] - Admin</title>

    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/smoothness/jquery-ui.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.12.0/css/all.css">

    <link rel="stylesheet" href="~/Admin/assets/css/admin-bootstrap.css" />
    <link rel="stylesheet" href="~/Admin/assets/css/admin.css" />

    <!--
        Section qui permet d'ajouter du contenu dans <head> à partir d'une vue
        Voir la vue Contact/Index.cshtml pour un exemple.
    -->
    @await RenderSectionAsync("Links", required: false)
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Admin" asp-controller="Home" asp-action="Index">ADMINISTRATION</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Menu" asp-action="List"><i class="far fa-list-alt"></i> LES CHOIX DE MENU</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Reservation" asp-action="List"><i class="far fa-list-alt"></i>LES RÉSERVATIONS</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            ASP.NET MVC - JeanLandreville
            <a asp-area="" asp-controller="Home" asp-action="Index">Client</a>
        </div>
    </footer>

    <!-- Placé à la fin du document pour un chargement plus rapide des pages -->
    <!-- Ordre : jQuery, Popper.js, puis Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    <!--
        Section qui permet d'ajouter du JavaScript à partir d'une vue
        Voir la vue Contact/Index.cshtml pour un exemple.
    -->
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>